export const images = {
  coast: '/images/airin-coast.jpg',
  portrait: '/images/airin-portrait.jpg',
  ritual: '/images/ritual.jpg',
  moon: '/images/moon.jpg',
  path: '/images/pathway.jpg',
};

const sharedSafety = 'Airin offers non-clinical wellness education, coaching, movement, meditation and contemplative experiences. This work does not diagnose, treat, prevent or cure disease and does not replace medical or mental-health care.';

export const offerings = [
  {
    slug: 'intuitive-session', number: '01', title: 'Intuitive Health & Energy Session', category: 'Private', audience: 'Open to everyone', location: 'Online worldwide', duration: '75 minutes', price: '$175 USD', status: 'Available by inquiry', image: images.ritual,
    intro: 'A focused, intuitive exploration of present wellbeing, habits and energy, followed by a grounded personal pathway for daily practice.',
    story: 'This one-time session is a spacious starting point for someone who wants to look at the whole picture before choosing a longer path. Airin listens across nourishment, daily rhythm, movement, stress and the language of the subtle body. The session is reflective and educational, never diagnostic.',
    includes: ['Pre-session wellness intake', 'Private live video session', 'Reflection across nourishment, habits and energy', 'Non-prescriptive daily-practice suggestions', 'A concise written integration roadmap'],
    forYou: 'You want a single point of clarity, a thoughtful outside perspective and practical next steps without beginning a longer program.',
    safety: 'This is not a medical scan and does not identify deficiencies or diagnose symptoms. Suspected deficiencies and persistent symptoms require assessment by a qualified clinician.', cta: 'Request an intuitive session'
  },
  {
    slug: 'mentoring', number: '02', title: 'One-to-One Mentoring', category: 'Private', audience: 'Open to everyone', location: 'Online worldwide', duration: '12 weeks', price: '$1,800 USD', status: 'Application open', image: images.portrait,
    intro: 'A sustained personal container weaving holistic health coaching, lifestyle guidance, movement, breath, nourishment and embodied daily ritual.',
    story: 'Mentoring creates the time required to move beyond inspiration and into lived change. Weekly sessions hold the larger arc, while simple practices meet the reality of work, relationships, energy and changing seasons. The pace is collaborative rather than prescriptive.',
    includes: ['Twelve weekly private sessions', 'Personal educational and practice plan', 'Movement, breath and meditation resources', 'Nourishment and lifestyle reflection', 'Boundaried WhatsApp support between sessions', 'Closing integration plan'],
    forYou: 'You are ready to practice consistently, value accountability and want individual support over several months.',
    safety: 'An intake establishes scope and screens for needs better served by a doctor, dietitian or mental-health professional. Mentoring never promises symptom reversal or clinical outcomes.', cta: 'Apply for mentorship'
  },
  {
    slug: 'sacred-fall-reset', number: '03', title: 'Sacred Fall Reset', category: 'Seasonal circle', audience: 'Women only', location: 'Live online · Goa time', duration: '4 weeks', price: '$395 USD', status: 'November cohort · dates to confirm', image: images.path,
    intro: 'The Wise Woman season: an intimate autumn circle for reflection, gentle nourishment, letting go and sustainable ritual.',
    story: 'Opening around the November new moon, the Sacred Fall Reset is the live autumn expression of Airin’s seasonal work. It combines weekly circles with meditation, tea education, movement, personal reflection and a supportive sisterhood. “Reset” means attentive routine support, not punishment or deprivation.',
    includes: ['Four live Zoom circles', 'New moon opening practice', 'Chakra-aligned guided meditations', 'Vedic-inspired seasonal teachings', 'Tea and nourishment education', 'Daily reflection and movement invitations', 'Closing integration circle'],
    forYou: 'You are a woman seeking a small, devoted seasonal group and a gentler relationship with change.',
    safety: 'There is no mandatory fasting. Herbs and significant dietary changes require appropriate screening, especially during pregnancy, medication use, chronic illness or eating-disorder recovery.', cta: 'Join the Fall interest list'
  },
  {
    slug: 'spring-maiden', number: '04', title: 'Spring · The Maiden', category: 'Seasonal circle', audience: 'Women only', location: 'Live online', duration: '4 weeks', price: '$395 USD', status: 'Seasonal waitlist', image: images.path,
    intro: 'Sacred Spring Awakening: lighter rhythms, emerging energy and the courage to begin again.', story: 'Spring is approached as an invitation to notice what wants to emerge. Weekly circles explore supportive routines, plant-rich nourishment, movement, hydration, reflection and small beginnings without turning the season into a restrictive cleanse.',
    includes: ['Weekly live circle', 'Spring movement and meditation', 'Hydration and nourishment education', 'Herbal-infusion guidance', 'Daily renewal prompts', 'Seasonal community space'], forYou: 'You want to renew your routines with companionship and realistic structure.', safety: 'The program makes no liver, gallbladder or detoxification claims. Restrictive diets and fasting are not required.', cta: 'Join the Spring waitlist'
  },
  {
    slug: 'summer-wild-woman', number: '05', title: 'Summer · The Wild Woman', category: 'Seasonal circle', audience: 'Women only', location: 'Live online', duration: '4 weeks', price: '$395 USD', status: 'Seasonal waitlist', image: images.coast,
    intro: 'Sacred Summer Radiance: creative movement, cooling rhythms and embodied confidence.', story: 'The summer circle turns toward expression and aliveness. Practices explore movement, sensual presence, cooling nourishment, journaling and the solar-plexus symbolism of agency and confidence.', includes: ['Weekly live circle', 'Expressive movement practice', 'Cooling drink and nourishment education', 'Solar-plexus-themed meditation', 'Journaling and creative prompts', 'Seasonal community space'], forYou: 'You want an expressive, body-positive summer practice held within a women’s circle.', safety: 'Practices can always be modified or skipped. Herbs require interaction checks; movement requires care with heat, injury and pregnancy.', cta: 'Join the Summer waitlist'
  },
  {
    slug: 'winter-mystic', number: '06', title: 'Winter · The Mystic', category: 'Seasonal circle', audience: 'Women only', location: 'Live online', duration: '4 weeks', price: '$395 USD', status: 'Seasonal waitlist', image: images.moon,
    intro: 'Deep Restoration Sanctuary: warmth, inward reflection and permission to move more slowly.', story: 'Winter offers another kind of intelligence. This lower-intensity circle centers rest, warm nourishment, contemplative practice, sleep-supportive routines and the value of an unhurried inner life.', includes: ['Weekly live circle', 'Restorative meditation', 'Gentle movement options', 'Warm meal and beverage inspiration', 'Sleep-routine education', 'Journaling and community'], forYou: 'You are drawn to a quiet seasonal container that does not demand constant output.', safety: 'The program does not claim to reset the nervous system or build cellular reserves. All dietary traditions and needs are respected.', cta: 'Join the Winter waitlist'
  },
  {
    slug: 'kundalini-tantra-yoga', number: '07', title: 'Kundalini Tantra Yoga', category: 'Movement', audience: 'Open to everyone', location: 'Goa & online', duration: '60 minutes', price: 'From $75 USD', status: 'Available by inquiry', image: images.coast,
    intro: 'A private movement practice informed by Airin’s long study of Kundalini and Tantric yoga.', story: 'Posture, breath, attention and rest are shaped around the person in the room. The practice can be strong or quiet, but its purpose is always deeper listening rather than performance.', includes: ['Arrival and movement check-in', 'Tailored posture sequence', 'Appropriate breath practice', 'Meditation and closing rest', 'Optional home-practice note'], forYou: 'You want a private, adaptable practice rather than a one-size-fits-all class.', safety: 'Injury, pregnancy and cardiovascular or respiratory concerns must be disclosed. Forceful breathing and breath retention are never assumed appropriate.', cta: 'Reserve a private class'
  },
  {
    slug: 'energy-healing', number: '08', title: 'Energy Healing', category: 'Private', audience: 'Open to everyone', location: 'Goa & online', duration: '60 minutes', price: '$125 USD', status: 'Available by inquiry', image: images.ritual,
    intro: 'A quiet guided session using breath, rest, attention and Airin’s energy-healing framework.', story: 'Energy healing is held as a contemplative and subjective experience. The session creates room to slow down, notice the subtle body and integrate through grounded reflection.', includes: ['Opening check-in', 'Guided breath and body awareness', 'Quiet energy-awareness practice', 'Integration time', 'Optional grounding practice'], forYou: 'You are comfortable with spiritual and energetic language and understand that experiences vary.', safety: 'Energy work does not treat trauma, pain or illness. Any in-person touch is optional and requires explicit consent.', cta: 'Request an energy session'
  },
  {
    slug: 'moon-circle', number: '09', title: 'Sacred Moon Circle', category: 'Lunar circle', audience: 'Women only', location: 'Live online', duration: '30–45 minutes', price: '$35 single · $300 for 8', status: 'Monthly · dates to confirm', image: images.moon,
    intro: 'A recurring rhythm of guided meditation, new-moon intention and full-moon reflection.', story: 'The circle meets live on Zoom around the new and full moons. No previous meditation experience is needed. Each gathering offers a simple threshold between the pace of ordinary life and a quieter inner rhythm.', includes: ['New-moon intention practice', 'Full-moon reflection practice', 'Live guided meditation', 'Journaling prompts', 'Optional circle sharing', 'Eight-session path available'], forYou: 'You want a regular women’s meditation practice with lunar rhythm and supportive connection.', safety: 'You may keep your eyes open, change position or leave at any time. Meditation is not crisis or mental-health treatment.', cta: 'Join the Moon Circle'
  },
  {
    slug: 'yoga-meditation-barre', number: '10', title: 'Yoga, Meditation & Barre', category: 'Movement', audience: 'Open to everyone', location: 'Goa & online', duration: '60 minutes', price: 'From $75 USD', status: 'Year-round', image: images.portrait,
    intro: 'Live movement, meditation, breathwork and special workshops for private clients and groups.', story: 'Each session is designed around the experience, energy and needs of the people present. Yoga and barre build different qualities; meditation and breath create the space to feel them.', includes: ['Movement check-in', 'Yoga or barre sequence', 'Optional breathwork', 'Guided meditation', 'Cool-down and integration', 'Private and group formats'], forYou: 'You want a stand-alone class, a private practice or a movement experience for your group.', safety: 'Injury and pregnancy information is collected before movement. Low-impact options and consent-based adjustments are always available.', cta: 'Find a class'
  },
  {
    slug: 'sip-cacao-meditate', number: '11', title: 'Sip Cacao & Meditate', category: 'Goa gathering', audience: 'Open to everyone', location: 'Anahata, Goa', duration: 'Approx. 90 minutes', price: '$45 USD', status: 'Monthly · date to confirm', image: images.ritual,
    intro: 'A heart-centered evening pairing ceremonial cacao with stillness, guided meditation and connection.', story: 'At Anahata, the symbolism of the heart chakra meets the grounded ritual of sharing cacao. The gathering makes room for quiet, reflection and optional conversation rather than promising a particular state.', includes: ['Clearly labeled cacao serving', 'Guided meditation', 'Quiet reflection', 'Optional community sharing', 'Sound component when announced', 'Cacao-free participation option'], forYou: 'You enjoy group meditation and can safely consume cacao, or prefer a cacao-free place in the circle.', safety: 'Cacao contains caffeine and theobromine. Ingredients and serving size are disclosed; seek medical advice for pregnancy, relevant heart conditions, allergies or medication interactions.', cta: 'Reserve a gathering seat'
  },
  {
    slug: 'five-day-reset', number: '12', title: 'Five-Day Elemental Reset', category: 'Self-guided', audience: 'Open to everyone', location: 'Online', duration: '5 days', price: '$79 USD', status: 'Early-access list', image: images.path,
    intro: 'Five days, five elements and one approachable daily ritual.', story: 'Earth, Water, Fire, Air and Akasha become themes for pausing, reflecting and returning to intentional routines. The self-paced format is concise by design and does not require fasting.', includes: ['Five daily lessons', 'One element and ritual per day', 'Journaling prompt', 'Gentle movement or breath option', 'Herbal-infusion alternative', 'Closing integration guide'], forYou: 'You want an accessible introduction before joining a live program.', safety: 'The reset does not reboot or detoxify the body. Every breath and beverage practice includes a simple alternative.', cta: 'Get early access'
  },
  {
    slug: 'embodied-woman', number: '13', title: 'Embodied Woman', category: 'Signature program', audience: 'Women only', location: 'Live online', duration: '10 weeks', price: '$995 USD', status: 'Waitlist open', image: images.portrait,
    intro: 'A signature journey through feminine embodiment, confidence, movement, nourishment and self-connection.', story: 'Embodied Woman is an invitational group process for women who want to inhabit their lives with greater presence. It explores movement, mindset, nourishment and feminine expression without positioning the group as trauma therapy.', includes: ['Ten weekly group sessions', 'Consent-based movement', 'Guided reflection and journaling', 'Nourishment education', 'Confidence and mindset practices', 'Private community space', 'Closing integration ritual'], forYou: 'You want a longer women’s group centered on embodiment and are comfortable choosing your own boundaries.', safety: 'This is not sexuality therapy, trauma treatment or mental-health care. Every practice is optional and consent-based.', cta: 'Join the Embodied Woman waitlist'
  },
  {
    slug: 'inner-fire-immersion', number: '14', title: 'Inner Fire Immersion', category: 'Bespoke immersion', audience: 'Open to everyone', location: 'Goa & selected destinations', duration: 'Tailored', price: 'Custom proposal', status: 'By application', image: images.coast,
    intro: 'A private or small-group journey shaped around movement, meditation, nourishing food, bodywork and place.', story: 'The immersion is designed after a planning conversation rather than sold as a fixed package. Goa is the natural home base, with selected destination experiences considered when logistics, practitioners and safety can be responsibly arranged.', includes: ['Private planning consultation', 'Tailored movement and meditation', 'Nourishing meals', 'Nature and place-based experiences', 'Energy work and optional bodywork', 'Dance or intimate workshops', 'Integration plan'], forYou: 'You want a higher-touch, customized experience and are able to travel safely.', safety: 'Every proposal must confirm credentials, consent, food requirements, accessibility, insurance, emergency arrangements and exact travel inclusions.', cta: 'Request an immersion proposal'
  },
];

export const retreats = [
  { slug: 'goa-new-beginnings', title: 'New Year, New Beginnings', date: 'January 14–18, 2027', duration: '5 days · 4 nights', price: 'Proposed from $1,650 USD', status: 'Interest list · details to confirm', image: images.coast, audience: 'Open to everyone', description: 'A restorative Goa pause with yoga, meditation, dance, conscious movement, sound, massage, nourishing food, nature and workshops.', includes: ['Dawn practice', 'Nourishing shared meals', 'Movement and meditation', 'Workshop or bodywork period', 'Nature and rest', 'Sunset practice', 'Evening ritual'], safety: 'Venue, room categories, transfers, insurance requirements, accessibility, food details and cancellation terms will be published before deposits are accepted.' },
  { slug: 'anahata-monthly', title: 'Anahata Wellness & Movement Retreat', date: 'Monthly · next date to confirm', duration: 'Weekend format proposed', price: 'Proposed from $295 USD', status: 'Interest list', image: images.path, audience: 'Open to everyone', description: 'An intimate Goa weekend centered on conscious movement, nourishment, meditation, reflection and rest.', includes: ['Yoga or conscious movement', 'Meditation and reflection', 'Nourishing meals', 'Nature time', 'Optional workshop', 'Sound or bodywork when listed'], safety: 'Each date will publish its exact day or residential format, venue, accessibility, food, bodywork consent and emergency arrangements.' },
];

export const articles = [
  { slug: 'seasonal-living', category: 'Seasonal practice', title: 'The Quiet Intelligence of Seasonal Living', intro: 'Seasonal living does not require a strict diet, a dramatic cleanse or a perfect morning routine. It can begin with attention.', image: images.path, paragraphs: ['Notice the temperature when you step outside, the time daylight fades, the foods naturally available and the amount of movement or rest your body welcomes. Choose one small response to what you notice.', 'A weekly check-in can make this practical. Ask: What is giving me energy? What is asking for less effort? What routine would make this week feel steadier? Write down one answer and choose one realistic action.', 'Seasonal practice is not a medical intervention, and nature does not ask everyone to follow the same rhythm. Health, work, caregiving, climate and access all shape what is possible. The aim is to meet your actual life with a little more care.'] },
  { slug: 'return-to-the-body', category: 'Embodiment', title: 'Five Small Rituals for Returning to Your Body', intro: 'Returning to the body can be simple. It does not require reaching a special state.', image: images.portrait, paragraphs: ['Feel your feet where they meet the floor. Take an unforced breath and let the exhale finish. Drink water slowly enough to notice its temperature. Look outside and name three things you see. Ask what would offer practical support in the next hour.', 'These are invitations rather than rules. A breath practice should never make you dizzy, and stillness is not comfortable for everyone. Keep your eyes open, move around or stop whenever you choose.', 'The purpose is not perfect calm. It is useful information about the present moment. Repeated gently, small pauses can shape a life through attention rather than pressure.'] },
  { slug: 'gentler-belly', category: 'Nourishment', title: 'A Gentler Conversation with the Belly', intro: 'The belly is often where wellness language becomes harsh. A gentler approach replaces judgment with observation.', image: images.ritual, paragraphs: ['Notice what a meal is like before, during and after eating. Were you hungry? Rushed? Satisfied? A brief note can reveal patterns without turning every sensation into a diagnosis.', 'Regular meals, adequate hydration, varied foods and enough time to eat are reasonable foundations for many people, but there is no universal plan. Culture, budget, allergies, medication, health conditions and eating-disorder history all matter.', 'Persistent pain, bleeding, vomiting, unexplained weight change or other concerning symptoms need medical attention. Curiosity can support a kinder relationship with food, but it should never delay qualified care.'] },
];

export { sharedSafety };
