export const siteUrl = 'https://airin-aquarius.vercel.app';

export const images = {
  coast: '/images/airin-coast.jpg',
  portrait: '/images/airin-portrait-v2.jpg',
  ritual: '/images/ritual.jpg',
  moon: '/images/moon.jpg',
  path: '/images/pathway.jpg',
};

export const contact = {
  email: 'healthcoach.airin@gmail.com',
  whatsapp: '18086343262',
  whatsappHref: 'https://wa.me/18086343262',
  instagram: 'https://www.instagram.com/sweetnsacred/',
  instagramHandle: '@sweetnsacred',
  maps: 'https://maps.app.goo.gl/8esgEWqfmnAfVz7S7',
  lat: 15.6674566,
  lng: 73.7137167,
  place: 'Casa Christavo, Junos Wado, Mandrem',
  listing: 'Yoga & Health Coach- Airin Aquarius',
  hours: 'From 07:00 IST',
};

export const sharedSafety =
  'Airin offers non-clinical wellness education, coaching, movement, meditation and contemplative experiences. This work does not diagnose, treat, prevent or cure disease and does not replace medical or mental-health care.';

export const elements = [
  {
    id: 'earth',
    name: 'Earth',
    role: 'The body',
    line: 'Nourishment, steadiness and strength.',
    copy: 'Laterite, roots, meals, sleep, the weight of being here.',
  },
  {
    id: 'water',
    name: 'Water',
    role: 'The feeling',
    line: 'Emotion, creativity and sensuality.',
    copy: 'Tide, cacao, the body’s weather, the courage to feel.',
  },
  {
    id: 'fire',
    name: 'Fire',
    role: 'The calling',
    line: 'Passion, confidence and life energy.',
    copy: 'Agni. Passion, confidence, spiritual dharma — the calling in the belly.',
  },
  {
    id: 'air',
    name: 'Air',
    role: 'The breath',
    line: 'Movement, spaciousness and breath.',
    copy: 'Palm wind, yoga, barre, the space between thoughts.',
  },
  {
    id: 'akasha',
    name: 'Akasha',
    role: 'The sacred',
    line: 'Ritual, presence and intuition.',
    copy: 'Moon, silence, the field around the body, the moment after the bell.',
  },
];

export const bellyEssay = {
  lead: 'The gut is the foundation of our health and energy.',
  body: [
    'It is where nutrients are absorbed, the immune system is cultivated, where hormones are regulated, and where the nervous system whispers its first language. In yoga, it is also the home of the solar plexus — the third chakra, the core fire, the seat of our energy, power and confidence. When the belly is alive, we thrive.',
    'The belly is more than digestion. It is a portal to your magic, your power, your confidence and your sexual nature. Heal digestive fire. Activate inner fire. A clear gut means a clear core — and a life that can feel sexy and alive again.',
    'The body knows how to heal itself. When we stop fighting it and begin working with nature — herbs and plants, clean food, clean water, rest, breath, movement, dance, sun, the rhythms of the moon — its intelligence emerges. We cleanse. We lighten the load. We clear the pathways. Once what does not belong can move, absorption returns. Energy returns. The fire in the belly relights.',
  ],
};

export const offerings = [
  {
    slug: 'intuitive-session',
    number: '01',
    title: 'Intuitive Health & Energy Session',
    category: 'Private',
    door: 'private',
    element: 'fire',
    audience: 'Open to everyone',
    location: 'Online worldwide',
    duration: '75 minutes',
    price: '$175 USD',
    status: 'Available by inquiry',
    image: images.ritual,
    intro:
      'A focused reading of your body, energy field and present habits — then a grounded pathway toward a clearer core and a livelier fire.',
    story:
      'This one-time session is a spacious starting point. Airin listens across nourishment, daily rhythm, movement, stress and the language of the subtle body. You leave with a personal roadmap — herbs and daily practices offered as education, never as a diagnosis.',
    includes: [
      'Pre-session wellness intake',
      'Private live video session',
      'Reflection across nourishment, habits and energy',
      'Non-prescriptive daily-practice suggestions',
      'A concise written integration roadmap',
    ],
    forYou:
      'You want a single point of clarity, a thoughtful outside perspective and practical next steps without beginning a longer program.',
    safety:
      'This is not a medical scan and does not identify deficiencies or diagnose symptoms. Suspected deficiencies and persistent symptoms require assessment by a qualified clinician.',
    cta: 'Request an intuitive session',
  },
  {
    slug: 'mentoring',
    number: '02',
    title: 'One-to-One Mentoring',
    category: 'Private',
    door: 'private',
    element: 'earth',
    audience: 'Open to everyone',
    location: 'Online worldwide',
    duration: '12 weeks',
    price: '$1,800 USD',
    status: 'Application open',
    image: images.portrait,
    intro:
      'A deep container of holistic coaching, intuitive scans, energy readings, gut restoration and the slow work of cleansing — so vitality can return at the cellular level of daily life.',
    story:
      'Mentoring is where Inner Fire Alchemy is practiced over months. We restore and activate agni, the digestive fire. We look at what the body is carrying. We work with clean eating, herbal remedies, and — when it is appropriate and screened — educational support around detoxing and fasting. Weekly sessions hold the larger arc: movement, breath, nervous system, mindset, and the feminine/masculine balance that lets a woman feel at home in her power. The pace is collaborative. The aim is lasting change, not a weekend high.',
    includes: [
      'Twelve weekly private sessions',
      'Intuitive health scans and energy readings',
      'Gut restoration and agni education',
      'Cleanse and fasting education when appropriate',
      'Tea remedies and herbal guidance',
      'Movement, dance, breath and meditation resources',
      'Boundaried WhatsApp support between sessions',
      'Closing integration plan',
    ],
    forYou: 'You are ready to practice consistently, value accountability and want a real dive into cleansing, gut health and embodied daily ritual.',
    safety:
      'An intake establishes scope and screens for needs better served by a doctor, dietitian or mental-health professional. Mentoring is educational coaching. It does not diagnose, treat or promise to reverse disease.',
    cta: 'Apply for mentorship',
  },
  {
    slug: 'sacred-fall-reset',
    number: '03',
    title: 'Sacred Fall Reset',
    category: 'Seasonal circle',
    door: 'circle',
    element: 'earth',
    season: 'autumn',
    audience: 'Women only',
    location: 'Live online · Goa time',
    duration: '4 weeks',
    price: '$395 USD',
    status: 'November cohort · dates to confirm',
    image: images.path,
    featured: true,
    intro:
      'The Wise Woman season: a seasonal cleanse for women — weekly protocols, tea remedies, sisterhood and a return to your fire.',
    story:
      'Opening around the November new moon, the Sacred Fall Reset is the live autumn expression of Airin’s seasonal work. Weekly Zoom gatherings, self-reflection, chakra-aligned meditations, energy work, Vedic-inspired teachings, nutrition guidelines, tea remedies, sacred ritual and movement. Weekly detox protocols are educational and body-tailored — not a punishment cleanse. A small circle of women, devoted together for the season.',
    includes: [
      'Four live Zoom circles',
      'New moon opening practice',
      'Weekly educational detox protocols',
      'Nutrition guidelines and tea remedies',
      'Chakra-aligned guided meditations',
      'Vedic-inspired seasonal teachings',
      'Sacred ritual and movement',
      'Closing integration circle',
    ],
    forYou:
      'You are a woman seeking a small, devoted seasonal group — tired of low energy or digestive heaviness, ready to return to your fire, confident and rooted.',
    safety:
      'There is no mandatory fasting. Herbs and significant dietary changes require appropriate screening, especially during pregnancy, medication use, chronic illness or eating-disorder recovery.',
    cta: 'Join the Fall interest list',
  },
  {
    slug: 'spring-maiden',
    number: '04',
    title: 'Spring · The Maiden',
    category: 'Seasonal circle',
    door: 'circle',
    element: 'air',
    season: 'spring',
    audience: 'Women only',
    location: 'Live online',
    duration: '4 weeks',
    price: '$395 USD',
    status: 'Seasonal waitlist',
    image: images.path,
    intro: 'Sacred Spring Awakening: lighter rhythms, emerging energy and the courage to begin again.',
    story:
      'Sacred Spring Awakening. Weekly circles explore lighter rhythms, plant-rich nourishment, movement, hydration, tea remedies and small beginnings. A spring protocol is offered as education — never as a forced fast.',
    includes: [
      'Weekly live circle',
      'Spring movement, dance and meditation',
      'Hydration and nourishment education',
      'Tea remedies and herbal-infusion guidance',
      'Educational seasonal protocol',
      'Daily renewal prompts',
      'Seasonal sisterhood space',
    ],
    forYou: 'You want to renew your routines with companionship and realistic structure.',
    safety: 'The program makes no liver, gallbladder or detoxification claims. Restrictive diets and fasting are not required.',
    cta: 'Join the Spring waitlist',
  },
  {
    slug: 'summer-wild-woman',
    number: '05',
    title: 'Summer · The Wild Woman',
    category: 'Seasonal circle',
    door: 'circle',
    element: 'fire',
    season: 'summer',
    audience: 'Women only',
    location: 'Live online',
    duration: '4 weeks',
    price: '$395 USD',
    status: 'Seasonal waitlist',
    image: images.coast,
    intro: 'Sacred Summer Radiance: creative movement, cooling rhythms and embodied confidence.',
    story:
      'The summer circle turns toward expression and aliveness. Practices explore movement, sensual presence, cooling nourishment, journaling and the solar-plexus symbolism of agency and confidence.',
    includes: [
      'Weekly live circle',
      'Expressive movement practice',
      'Cooling drink and nourishment education',
      'Solar-plexus-themed meditation',
      'Journaling and creative prompts',
      'Seasonal community space',
    ],
    forYou: 'You want an expressive, body-positive summer practice held within a women’s circle.',
    safety:
      'Practices can always be modified or skipped. Herbs require interaction checks; movement requires care with heat, injury and pregnancy.',
    cta: 'Join the Summer waitlist',
  },
  {
    slug: 'winter-mystic',
    number: '06',
    title: 'Winter · The Mystic',
    category: 'Seasonal circle',
    door: 'circle',
    element: 'water',
    season: 'winter',
    audience: 'Women only',
    location: 'Live online',
    duration: '4 weeks',
    price: '$395 USD',
    status: 'Seasonal waitlist',
    image: images.moon,
    intro: 'Deep Restoration Sanctuary: warmth, inward reflection and permission to move more slowly.',
    story:
      'Winter offers another kind of intelligence. This lower-intensity circle centers rest, warm nourishment, contemplative practice, sleep-supportive routines and the value of an unhurried inner life.',
    includes: [
      'Weekly live circle',
      'Restorative meditation',
      'Gentle movement options',
      'Warm meal and beverage inspiration',
      'Sleep-routine education',
      'Journaling and community',
    ],
    forYou: 'You are drawn to a quiet seasonal container that does not demand constant output.',
    safety:
      'The program does not claim to reset the nervous system or build cellular reserves. All dietary traditions and needs are respected.',
    cta: 'Join the Winter waitlist',
  },
  {
    slug: 'kundalini-tantra-yoga',
    number: '07',
    title: 'Kundalini Tantra Yoga',
    category: 'Movement',
    door: 'private',
    element: 'fire',
    audience: 'Open to everyone',
    location: 'Goa & online',
    duration: '60 minutes',
    price: 'From $75 USD',
    status: 'Available by inquiry',
    image: images.coast,
    intro: 'A private movement practice informed by twenty years of Kundalini and Tantric yoga — a moving prayer for the spine, the breath and the fire in the belly.',
    story:
      'Posture, breath, attention and rest are shaped around the person in the room. The practice can be strong or quiet, but its purpose is always deeper listening rather than performance.',
    includes: [
      'Arrival and movement check-in',
      'Tailored posture sequence',
      'Appropriate breath practice',
      'Meditation and closing rest',
      'Optional home-practice note',
    ],
    forYou: 'You want a private, adaptable practice rather than a one-size-fits-all class.',
    safety:
      'Injury, pregnancy and cardiovascular or respiratory concerns must be disclosed. Forceful breathing and breath retention are never assumed appropriate.',
    cta: 'Reserve a private class',
  },
  {
    slug: 'energy-healing',
    number: '08',
    title: 'Energy Healing',
    category: 'Private',
    door: 'private',
    element: 'akasha',
    audience: 'Open to everyone',
    location: 'Goa & online',
    duration: '60 minutes',
    price: '$125 USD',
    status: 'Available by inquiry',
    image: images.ritual,
    intro: 'A quiet guided session using breath, rest, attention and Airin’s energy-healing framework.',
    story:
      'Energy healing is held as a contemplative and subjective experience. The session creates room to slow down, notice the subtle body and integrate through grounded reflection.',
    includes: [
      'Opening check-in',
      'Guided breath and body awareness',
      'Quiet energy-awareness practice',
      'Integration time',
      'Optional grounding practice',
    ],
    forYou: 'You are comfortable with spiritual and energetic language and understand that experiences vary.',
    safety: 'Energy work does not treat trauma, pain or illness. Any in-person touch is optional and requires explicit consent.',
    cta: 'Request an energy session',
  },
  {
    slug: 'moon-circle',
    number: '09',
    title: 'Sacred Moon Circle',
    category: 'Lunar circle',
    door: 'circle',
    element: 'akasha',
    audience: 'Women only',
    location: 'Live online',
    duration: '30–45 minutes',
    price: '$35 single · $300 for 8',
    status: 'Monthly · dates to confirm',
    image: images.moon,
    intro: 'A monthly women’s gathering: meditation, sisterhood, feminine wisdom, journaling and inner rhythm.',
    story:
      'The circle meets live on Zoom around the new and full moons. Guided meditation, reflection, women’s health education, feminine wisdom, intention setting and a supportive community. No previous meditation experience is needed.',
    includes: [
      'New-moon intention practice',
      'Full-moon reflection practice',
      'Live guided meditation',
      'Women’s health and feminine-wisdom teaching',
      'Journaling prompts',
      'Optional circle sharing',
      'Eight-session path available',
    ],
    forYou: 'You want a regular women’s meditation practice with lunar rhythm and supportive connection.',
    safety: 'You may keep your eyes open, change position or leave at any time. Meditation is not crisis or mental-health treatment.',
    cta: 'Join the Moon Circle',
  },
  {
    slug: 'yoga-meditation-barre',
    number: '10',
    title: 'Yoga, Dance, Meditation & Barre',
    category: 'Movement',
    door: 'private',
    element: 'air',
    audience: 'Open to everyone',
    location: 'Goa & online',
    duration: '60 minutes',
    price: 'From $75 USD',
    status: 'Year-round',
    image: images.portrait,
    intro: 'Live yoga, dance, barre, meditation, breathwork and special workshops — in Goa, online, or as a private class.',
    story:
      'The body was made to move. Yoga and barre build different qualities; dance returns pleasure and rhythm; meditation and breath create the space to feel them. Each session is designed around the people in the room.',
    includes: [
      'Movement check-in',
      'Yoga, dance or barre sequence',
      'Optional breathwork',
      'Guided meditation',
      'Cool-down and integration',
      'Private, group and workshop formats',
    ],
    forYou: 'You want a stand-alone class, a private practice or a movement experience for your group.',
    safety:
      'Injury and pregnancy information is collected before movement. Low-impact options and consent-based adjustments are always available.',
    cta: 'Find a class',
  },
  {
    slug: 'sip-cacao-meditate',
    number: '11',
    title: 'Sip Cacao & Meditate',
    category: 'Goa gathering',
    door: 'place',
    element: 'water',
    audience: 'Open to everyone',
    location: 'Anahata, Goa',
    duration: 'Approx. 90 minutes',
    price: '$45 USD',
    status: 'Monthly · date to confirm',
    image: images.ritual,
    intro:
      'A heart-centered evening at Anahata — the heart chakra — pairing ceremonial cacao with stillness, guided meditation and connection.',
    story:
      'At Anahata, the symbolism of the heart chakra meets the grounded ritual of sharing cacao. The gathering makes room for quiet, reflection and optional conversation rather than promising a particular state. A cacao-free place in the circle is always available.',
    includes: [
      'Clearly labeled cacao serving',
      'Guided meditation',
      'Quiet reflection',
      'Optional community sharing',
      'Sound component when announced',
      'Cacao-free participation option',
    ],
    forYou: 'You enjoy group meditation and can safely consume cacao, or prefer a cacao-free place in the circle.',
    safety:
      'Cacao contains caffeine and theobromine. Ingredients and serving size are disclosed; seek medical advice for pregnancy, relevant heart conditions, allergies or medication interactions.',
    cta: 'Reserve a gathering seat',
  },
  {
    slug: 'five-day-reset',
    number: '12',
    title: 'Five-Day Elemental Reset',
    category: 'Self-guided',
    door: 'circle',
    element: 'earth',
    audience: 'Open to everyone',
    location: 'Online',
    duration: '5 days',
    price: '$79 USD',
    status: 'Early-access list',
    image: images.path,
    coming: true,
    intro: 'Five days, five elements and one approachable daily ritual.',
    story:
      'Earth, Water, Fire, Air and Akasha become themes for pausing, reflecting and returning to intentional routines. The self-paced format is concise by design and does not require fasting.',
    includes: [
      'Five daily lessons',
      'One element and ritual per day',
      'Journaling prompt',
      'Gentle movement or breath option',
      'Herbal-infusion alternative',
      'Closing integration guide',
    ],
    forYou: 'You want an accessible introduction before joining a live program.',
    safety: 'The reset does not reboot or detoxify the body. Every breath and beverage practice includes a simple alternative.',
    cta: 'Get early access',
  },
  {
    slug: 'embodied-woman',
    number: '13',
    title: 'Embodied Woman',
    category: 'Signature program',
    door: 'circle',
    element: 'water',
    audience: 'Women only',
    location: 'Live online',
    duration: '10 weeks',
    price: '$995 USD',
    status: 'Waitlist open',
    image: images.portrait,
    coming: true,
    intro:
      'A 10-week journey into feminine embodiment, sacred sexuality, vitality, confidence, movement, mindset, nervous system, nourishment and living from deep self-connection.',
    story:
      'Embodied Woman is Airin’s coming signature program: a transformational container for cultivating Divine Feminine and balancing masculine and feminine energies. It explores movement, dance, mindset, nourishment and expression. It is invitational group process — not sexuality therapy or trauma treatment.',
    includes: [
      'Ten weekly group sessions',
      'Consent-based movement',
      'Guided reflection and journaling',
      'Nourishment education',
      'Confidence and mindset practices',
      'Private community space',
      'Closing integration ritual',
    ],
    forYou: 'You want a longer women’s group centered on embodiment and are comfortable choosing your own boundaries.',
    safety: 'This is not sexuality therapy, trauma treatment or mental-health care. Every practice is optional and consent-based.',
    cta: 'Join the Embodied Woman waitlist',
  },
  {
    slug: 'inner-fire-immersion',
    number: '14',
    title: 'Inner Fire Immersion',
    category: 'Bespoke immersion',
    door: 'place',
    element: 'earth',
    audience: 'Open to everyone',
    location: 'Goa & selected destinations',
    duration: 'Tailored',
    price: 'Custom proposal',
    status: 'By application',
    image: images.coast,
    intro:
      'A private or small-group journey shaped around movement, meditation, nourishing food, bodywork and place.',
    story:
      'The immersion is designed after a planning conversation rather than sold as a fixed package. Goa is the natural home base, with selected destination experiences considered when logistics, practitioners and safety can be responsibly arranged.',
    includes: [
      'Private planning consultation',
      'Tailored movement and meditation',
      'Nourishing meals',
      'Nature and place-based experiences',
      'Energy work and optional bodywork',
      'Dance or intimate workshops',
      'Integration plan',
    ],
    forYou: 'You want a higher-touch, customized experience and are able to travel safely.',
    safety:
      'Every proposal must confirm credentials, consent, food requirements, accessibility, insurance, emergency arrangements and exact travel inclusions.',
    cta: 'Request an immersion proposal',
  },
];

export const retreats = [
  {
    slug: 'goa-new-beginnings',
    title: 'New Year, New Beginnings',
    date: 'January 14–18, 2027',
    duration: '5 days · 4 nights',
    price: 'Proposed from $1,650 USD',
    status: 'Interest list · details to confirm',
    image: images.coast,
    audience: 'Open to everyone',
    description:
      'A restorative Goa pause with yoga, meditation, dance, conscious movement, sound, massage, nourishing food, nature and workshops.',
    includes: [
      'Dawn practice',
      'Nourishing shared meals',
      'Movement and meditation',
      'Workshop or bodywork period',
      'Nature and rest',
      'Sunset practice',
      'Evening ritual',
    ],
    rhythm: [
      'Dawn practice',
      'Seasonal breakfast',
      'Workshop or bodywork',
      'Rest, water, nature',
      'Sunset movement',
      'Shared evening ritual',
    ],
    safety:
      'Venue, room categories, transfers, insurance requirements, accessibility, food details and cancellation terms will be published before deposits are accepted.',
  },
  {
    slug: 'anahata-monthly',
    title: 'Anahata Wellness, Detox & Movement Retreat',
    date: 'Monthly · next date to confirm',
    duration: 'Weekend format proposed',
    price: 'Proposed from $295 USD',
    status: 'Interest list',
    image: images.path,
    audience: 'Open to everyone',
    description:
      'An intimate Goa weekend of conscious movement, dance, nourishing food, meditation and an educational detox rhythm — held at Anahata.',
    includes: [
      'Yoga, dance or conscious movement',
      'Meditation and reflection',
      'Nourishing meals',
      'Educational detox and tea guidance',
      'Nature time',
      'Optional workshop, sound or bodywork when listed',
    ],
    safety:
      'Each date will publish its exact day or residential format, venue, accessibility, food, bodywork consent and emergency arrangements.',
  },
];

export const articles = [
  {
    slug: 'seasonal-living',
    category: 'Seasonal practice',
    botanical: 'hibiscus',
    title: 'The Quiet Intelligence of Seasonal Living',
    intro: 'Seasonal living does not require a strict diet, a dramatic cleanse or a perfect morning routine. It can begin with attention.',
    image: images.path,
    paragraphs: [
      'Notice the temperature when you step outside, the time daylight fades, the foods naturally available and the amount of movement or rest your body welcomes. Choose one small response to what you notice.',
      'A weekly check-in can make this practical. Ask: What is giving me energy? What is asking for less effort? What routine would make this week feel steadier? Write down one answer and choose one realistic action.',
      'Seasonal practice is not a medical intervention, and nature does not ask everyone to follow the same rhythm. Health, work, caregiving, climate and access all shape what is possible. The aim is to meet your actual life with a little more care.',
    ],
  },
  {
    slug: 'return-to-the-body',
    category: 'Embodiment',
    botanical: 'frangipani',
    title: 'Five Small Rituals for Returning to Your Body',
    intro: 'Returning to the body can be simple. It does not require reaching a special state.',
    image: images.portrait,
    paragraphs: [
      'Feel your feet where they meet the floor. Take an unforced breath and let the exhale finish. Drink water slowly enough to notice its temperature. Look outside and name three things you see. Ask what would offer practical support in the next hour.',
      'These are invitations rather than rules. A breath practice should never make you dizzy, and stillness is not comfortable for everyone. Keep your eyes open, move around or stop whenever you choose.',
      'The purpose is not perfect calm. It is useful information about the present moment. Repeated gently, small pauses can shape a life through attention rather than pressure.',
    ],
  },
  {
    slug: 'gentler-belly',
    category: 'Nourishment',
    botanical: 'tulsi',
    title: 'A Gentler Conversation with the Belly',
    intro: 'The belly is often where wellness language becomes harsh. A gentler approach replaces judgment with observation.',
    image: images.ritual,
    paragraphs: [
      'Notice what a meal is like before, during and after eating. Were you hungry? Rushed? Satisfied? A brief note can reveal patterns without turning every sensation into a diagnosis.',
      'Regular meals, adequate hydration, varied foods and enough time to eat are reasonable foundations for many people, but there is no universal plan. Culture, budget, allergies, medication, health conditions and eating-disorder history all matter.',
      'Persistent pain, bleeding, vomiting, unexplained weight change or other concerning symptoms need medical attention. Curiosity can support a kinder relationship with food, but it should never delay qualified care.',
    ],
  },
  {
    slug: 'agni-and-the-gut',
    category: 'Gut health',
    botanical: 'tulsi',
    title: 'Agni: Why the Belly Is the Inner Fire',
    intro: 'In yoga the solar plexus is the seat of power. In daily life it is also where we digest food, feeling and choice.',
    image: images.ritual,
    paragraphs: [
      'Airin calls this Inner Fire Alchemy for a reason. When digestion is heavy, energy drops, mood swings, skin flares and confidence often follow. Her own path — a long cleanse after years of bloating, eczema and fog — is why the work begins in the gut.',
      'Practically, tending agni can look like regular meals, warm food when the body asks for it, herbs and teas as education, less of what inflames you, and enough rest for the nervous system to stop gripping the belly. A seasonal cleanse is one way in. It is not the only way, and it is never a contest.',
      'This is not a diagnosis of parasites, deficiency or disease. Persistent or severe symptoms belong with a clinician. Coaching can sit beside that care; it cannot replace it.',
    ],
  },
  {
    slug: 'tea-remedies',
    category: 'Herbal tea',
    botanical: 'lotus',
    title: 'Tea as Daily Medicine — Without the Myth',
    intro: 'A cup can be ritual and plant education. It is not a cure in a mug.',
    image: images.ritual,
    paragraphs: [
      'Seasonal circles and mentoring include tea remedies: simple infusions that match the time of year — lighter and bitter in spring, cooling in summer, grounding in autumn, warming in winter. The point is rhythm and attention, not a secret formula.',
      'Ingredients, serving size and who should avoid a plant matter. Pregnancy, medication and allergies change the picture. Airin discloses what she offers and will not push a herb that has not been screened for you.',
      'If a tea is part of your protocol, treat it as food-level support. Anything stronger belongs in a conversation with a qualified practitioner.',
    ],
  },
  {
    slug: 'breath-and-nervous-system',
    category: 'Breath & nervous system',
    botanical: 'coconut',
    title: 'Breath Is How the Nervous System Speaks',
    intro: 'Regulation is not a personality trait. It is a practice you can modify or stop.',
    image: images.portrait,
    paragraphs: [
      'Cleansing the body without soothing the nervous system is how people burn out on wellness. Breath, rest, and simple orientation to the room are part of every container Airin holds — yoga, moon circle, mentoring, cacao evenings.',
      'A useful breath is unforced. If you feel dizzy, tingling or panicked, stop. Keep your eyes open. Sit instead of lying down. Nothing in this work requires you to “go deeper” than feels safe.',
      'Meditation and breath are not crisis care. If you are in acute distress, contact local emergency or mental-health services.',
    ],
  },
  {
    slug: 'divine-feminine',
    category: 'Women’s health',
    botanical: 'hibiscus',
    title: 'Divine Feminine, Without the Performance',
    intro: 'With women, Airin works toward more Divine Feminine — and a kinder balance with the masculine.',
    image: images.portrait,
    paragraphs: [
      'The Doc is plain: help women reconnect with their bodies, restore vitality, and feel sexy and alive again. That is not a costume. It is digestion, cycle literacy, rest, movement, pleasure, and the confidence that returns when the belly is no longer a battlefield.',
      'Masculine energy here means structure, follow-through, the container. Feminine means feeling, creativity, cyclical time. Most of us are asked to live in only one. Seasonal circles, moon gatherings and Embodied Woman are places to practice both.',
      'Private work remains open to everyone. The women-only rooms are named as such so no one has to guess.',
    ],
  },
  {
    slug: 'mindset-and-manifestation',
    category: 'Mindset',
    botanical: 'frangipani',
    title: 'Mindset Is a Daily Ritual, Not a Spell',
    intro: 'Manifestation, in this practice, is what happens when the body is resourced enough to follow a true yes.',
    image: images.moon,
    paragraphs: [
      'When the gut is overloaded and the nervous system is braced, “think positive” is another demand. Airin’s work flips the order: nourish, cleanse what you can, move, sleep — then notice what you actually want.',
      'Journaling, new-moon intention and full-moon release are tools for that noticing. They do not replace money, medicine or boundaries. They do give a place to hear yourself.',
      'If mindset work ever feels like self-blame, put the notebook down. The sanctuary is not another performance.',
    ],
  },
  {
    slug: 'sacred-daily-ritual',
    category: 'Ritual',
    botanical: 'lotus',
    title: 'Sacred Living Is Made of Ordinary Hours',
    intro: 'Akasha, in the five elements, is ritual, presence and intuition — usually smaller than we think.',
    image: images.moon,
    paragraphs: [
      'A candle, a cup of tea, five minutes of breath, a walk at dusk, dancing in the kitchen: these are the sacred daily rituals the brand is built on. They work because they repeat, not because they are dramatic.',
      'Seasonal cleanses and moon circles simply give those hours a shared clock. You can keep a ritual after the Zoom ends. You can also change it.',
      'Ritual is not a religion test. Bring your own faith, or none. The invitation is attention.',
    ],
  },
  {
    slug: 'dance-as-medicine',
    category: 'Dance & movement',
    botanical: 'banana',
    title: 'Dance Is Part of the Medicine',
    intro: 'She is a lover of dance and the ocean. Movement in this work is not only asana.',
    image: images.coast,
    paragraphs: [
      'Yoga, barre and conscious dance all appear in classes, retreats and the summer Wild Woman circle. Dance returns rhythm, pleasure and the simple fact of being in a body that can take up space.',
      'No performance standard. You can sway, sit, or mark the rhythm with a hand. Injury and pregnancy change the shape; they do not exclude you from the room.',
      'If you want movement without a cleanse, start with a private yoga or dance session, or ask for the next Anahata weekend.',
    ],
  },
  {
    slug: 'yoga-as-homecoming',
    category: 'Yoga',
    botanical: 'areca',
    title: 'Yoga as the Path That Brought Her Home',
    intro: 'The mat was never a brand. It was how a young woman in Hawaii began to heal childhood wounding.',
    image: images.portrait,
    paragraphs: [
      'Twenty years of practice, fifteen years teaching, lineages in Bali, Kundalini Tantra, and the quiet of daily class: yoga in this house is a moving prayer, not a workout badge.',
      'Private Kundalini Tantra sessions, group classes, retreats and the breath inside a cleanse all come from that same love. Strength and softness are both allowed.',
      'Forceful breath and long retention are never assumed. Tell Airin what your body is carrying before you begin.',
    ],
  },
];

export const doors = [
  {
    id: 'private',
    title: 'Private work',
    line: 'Scans, mentoring, cleanse education, yoga and dance.',
    to: '/offerings?door=private',
    emblem: 'lamp',
  },
  {
    id: 'circle',
    title: 'Women’s circles',
    line: 'Seasons, moons, Divine Feminine, sisterhood.',
    to: '/seasons',
    emblem: 'wheel',
  },
  {
    id: 'place',
    title: 'Immersions in Goa',
    line: 'Leave the noise. Keep what matters.',
    to: '/retreats',
    emblem: 'path',
  },
];

export const aboutChapters = [
  {
    id: 'maryland',
    land: 'Maryland',
    botanical: 'tulsi',
    kicker: 'The beginning',
    title: 'A girl who left, and kept leaving toward the sea.',
    body: 'Airin’s story began in Maryland. Working as a model from fifteen, she arrived in Hawaii at twenty-two and never went back. The islands caught her with salt air and a slower rhythm, and she chose to stay.',
  },
  {
    id: 'hawaii',
    land: 'Hawaii',
    botanical: 'frangipani',
    kicker: 'Salt and sail',
    title: 'The ocean became the first teacher.',
    body: 'Island life taught her by keeping her close to earth and sea: hiking ridgelines, surfing at dawn, sailing the channels — including a passage from Hawaii to Fiji — fishing deep water. Yoga became a path home through early wounds and into a more peaceful relationship with herself.',
  },
  {
    id: 'study',
    land: 'Bali · Thailand · Hawaii · New York',
    botanical: 'lotus',
    kicker: 'The year of study',
    title: 'Lineages gathered, one after another.',
    body: 'In 2011 she travelled to study in earnest. Tantric yoga in Bali. Another Kundalini Tantra school. Three months in a village with a Balinese medicine man, where she was initiated as a spiritual healer. Energy and chakra healing with a Thai healer. Massage school in Hawaii. Certification as a holistic health coach through a New York program, with further study in gut health. Seven years apprenticed to a medical intuitive.',
  },
  {
    id: 'collapse',
    land: 'The café, then the body',
    botanical: 'hibiscus',
    kicker: 'The turning',
    title: 'The fire went out. Then it was tended.',
    body: 'She helped co-create an organic Indian café in Hawaii, supporting local farmers. Even living what looked like the cleanest island life, her body began to speak loudly — constant bloating, eczema across face, neck, hands and arms, hormonal imbalance, brain fog, headaches, gluten reaction, anxiety, intense mood swings, chronic fatigue. Doctors offered medication. She refused. She cleansed for nearly five months, discovered she had been carrying a parasitic worm, and through that long clearing reversed those symptoms. That journey birthed the work as a detox and gut coach. Inner Fire Alchemy is not a slogan. It is a life she had to walk.',
  },
  {
    id: 'goa',
    land: 'Mandrem, Goa',
    botanical: 'coconut',
    kicker: 'Today',
    title: 'The work now has an address.',
    body: 'Nearly two decades of practice now live in private coaching, movement, dance, meditation, women’s circles and retreats from Mandrem — and online worldwide. With women, the work also cultivates Divine Feminine and a healthier balance of masculine and feminine energies. Yoga, breath and guided meditation remain part of every container, because healing is never only physical. She still loves dance. She still loves the ocean.',
  },
];

export const credentials = [
  'Certified Holistic Health Coach',
  'Tantric Yoga Teacher',
  'Meditation / Mystic Guide',
  'Women’s Wellness Mentor',
  'Further study in gut health',
  'Training in energy and chakra healing',
  'Massage training in Hawaii',
  'Seven years apprenticed to a medical intuitive',
];

export { sharedSafety as safetyLine };
